"""Governed CryptoPulse LLM analysis contracts, provider client, and offline pipeline."""

from .claim_plan_render import (
    ClaimPlanRender,
    ClaimPlanRenderError,
    RenderedClaim,
    render_claim_plan,
)
from .claim_plan_validation import (
    claim_source_disagreement_eligible,
    is_source_disagreement_pair,
    iter_plan_claims,
    validate_claim_plan,
)
from .contracts import (
    ANALYSIS_SCHEMA_VERSION,
    CLAIM_PLAN_COMPARISON_RELATIONS,
    CLAIM_PLAN_CONFIDENCE_LEVELS,
    CLAIM_PLAN_INTENTS,
    CLAIM_PLAN_PROMPT_VERSION,
    CLAIM_PLAN_RENDERER_VERSION,
    CLAIM_PLAN_SCHEMA_VERSION,
    CLAIM_PLAN_SECTION_KINDS,
    CLAIM_TYPES,
    EVIDENCE_ID_PATTERN,
    EVIDENCE_SCHEMA_VERSION,
    PROMPT_VERSION,
    PROVENANCE_SCHEMA_VERSION,
    canonical_json_bytes,
    content_sha256,
    evidence_id,
)
from .diagnostics import Diagnostic, ValidationReport
from .generation_config import (
    ConfigurationError,
    GenerationConfig,
    ProviderPolicy,
    load_generation_config,
    model_matches,
)
from .openrouter_client import (
    AuthenticationGenerationError,
    BillingGenerationError,
    CostLimitError,
    GenerationError,
    GenerationMetadata,
    GenerationResult,
    GenerationTimeoutError,
    IneligibleRoutingError,
    InputLimitError,
    InvalidResponseError,
    MissingSecretError,
    OpenRouterClient,
    ProviderGenerationError,
    TransportGenerationError,
    build_request_body,
    render_prompt,
)
from .pipeline import PipelineResult, load_json, process_analysis
from .render import InvalidAnalysisError, render_markdown
from .validate import validate_analysis

__all__ = [
    "ANALYSIS_SCHEMA_VERSION",
    "CLAIM_PLAN_COMPARISON_RELATIONS",
    "CLAIM_PLAN_CONFIDENCE_LEVELS",
    "CLAIM_PLAN_INTENTS",
    "CLAIM_PLAN_PROMPT_VERSION",
    "CLAIM_PLAN_RENDERER_VERSION",
    "CLAIM_PLAN_SCHEMA_VERSION",
    "CLAIM_PLAN_SECTION_KINDS",
    "CLAIM_TYPES",
    "EVIDENCE_ID_PATTERN",
    "EVIDENCE_SCHEMA_VERSION",
    "PROMPT_VERSION",
    "PROVENANCE_SCHEMA_VERSION",
    "AuthenticationGenerationError",
    "BillingGenerationError",
    "ClaimPlanRender",
    "ClaimPlanRenderError",
    "ConfigurationError",
    "CostLimitError",
    "Diagnostic",
    "GenerationConfig",
    "GenerationError",
    "GenerationMetadata",
    "GenerationResult",
    "GenerationTimeoutError",
    "IneligibleRoutingError",
    "InputLimitError",
    "InvalidAnalysisError",
    "InvalidResponseError",
    "MissingSecretError",
    "OpenRouterClient",
    "PipelineResult",
    "ProviderGenerationError",
    "ProviderPolicy",
    "RenderedClaim",
    "TransportGenerationError",
    "ValidationReport",
    "build_request_body",
    "canonical_json_bytes",
    "claim_source_disagreement_eligible",
    "content_sha256",
    "evidence_id",
    "is_source_disagreement_pair",
    "iter_plan_claims",
    "load_generation_config",
    "load_json",
    "model_matches",
    "process_analysis",
    "render_claim_plan",
    "render_markdown",
    "render_prompt",
    "validate_analysis",
    "validate_claim_plan",
]
